#!/usr/bin/env sh

PINENTRY_TUI=pinentry

PINENTRY_GUI= # TODO: define linux default

if [ "$(uname)" = "Darwin" ]; then
	pinentry-mac --version > /dev/null 2>&1 && PINENTRY_GUI='pinentry-mac'
fi

if tty -s; then
	eval "$PINENTRY_TUI $*"
else
	eval "$PINENTRY_GUI $*"
fi
