[tools]
bun = "latest"
fzf = "latest"
go = "latest"
# jq = "latest" # TODO: watch https://github.com/lsanwick/asdf-jq/issues/5
neovim = "latest"
node = "latest"
opam = "latest"
python = "latest"
# shellcheck = "latest" # TODO: watch https://github.com/koalaman/shellcheck/pull/2736
stylua = "latest"
zig = "latest"
yq = "latest"
