[tools]
act = "latest"
bun = "latest"
ffmpeg = "latest"
fzf = "latest"
gitleaks = "latest"
go = "latest"
# jq = "latest" # TODO: watch https://github.com/lsanwick/asdf-jq/issues/5
neovim = "latest"
node = "latest"
opam = "latest"
python = "latest"
# shellcheck = "latest" # TODO: watch https://github.com/koalaman/shellcheck/pull/2736
stylua = "latest"
tmux = "latest"
zig = "latest"
yq = "latest"

## Not working on Mac Apple Silicon ##
# imagemagick = "latest"
