name: Lint & Format

on: [push, pull_request]

jobs:
  formatters:
    name: Beautysh & stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v3
      - name: Run shfmt
        if: always()
        run: |
            shfmt --indent 4 --simplify --case-indent --binary-next-line --space-redirects \
                $(find . -not -path "./.git/*" -not -path "./shell/zsh/.zsh-plugins/*" -not -path "./.config/tmux/plugins/*" \( -name "*.sh" -o -name "*.bash" -o -name "*.zsh" \))
      - name: Run stylua
        if: always()
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: . -c

  linters:
    name: Shellcheck & Luacheck
    runs-on: ubuntu-latest
    needs: [formatters]
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck (no ZSH)
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./shell/zsh/.zshrc
            ./**/*.zsh
        env:
          # SC1091: Not following. -- is fixed locally but CI still fails
          SHELLCHECK_OPTS: -e SC1091
      - name: Run ShellCheck (only ZSH)
        if: always()
        uses: ludeeus/action-shellcheck@master
        env:
          # SC1091: Not following. -- is fixed locally but CI still fails
          # -s bash: force checks as bash because of zsh not supported
          SHELLCHECK_OPTS: -e SC1091 -s bash
      - name: Luacheck linter
        if: always()
        uses: lunarmodules/luacheck@v1
        with:
          args: . --codes --config .config/nvim/.luacheckrc
