name: Lint & Format

on: [push, pull_request]

jobs:
  formatters:
    name: Beautysh & stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Beautysh
        uses: illvart/beautysh-action@latest
        with: # not in .git and not in zsh-plugins
          args: -i 2 -s paronly $(find . -not -path "./.git/*" -not -path "./zsh-plugins/*" \( -name "*.sh" -o -name "*.bash" -o -name "*.zsh" \))
      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[auto] ci: beautify code'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linters:
    name: Shellcheck & Luacheck
    runs-on: ubuntu-latest
    needs: [formatters]
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck (no ZSH)
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./shell/zsh/.zshrc
            ./**/*.zsh
        env:
          # SC1091: Not following.
          SHELLCHECK_OPTS: -e SC1091
      - name: Run ShellCheck (only ZSH)
        if: always()
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths:  >-
            !./shell/zsh/.zshrc
            !./**/*.zsh
        env:
          # SC1091: Not following.
          # -s bash: force checks as bash because of zsh not supported
          SHELLCHECK_OPTS: -e SC1091 -s bash
      - name: Luacheck linter
        if: always()
        uses: lunarmodules/luacheck@v1
        with:
          args: . --globals 'vim' --codes
