name: Lint

on: [push, pull_request]

jobs:
  shellcheck:
    name: Shellcheck & Luacheck linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
