name: Lint & Format

on: [push, pull_request]

jobs:
  formatters:
    name: shfmt & stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - uses: mfinelli/setup-shfmt@v3

      - name: Run shfmt
        # fix command `shfmt -w -i 4 -s -bn -ci -sr -kp .`
        run: |
          SUPPORTED_SHELLS="sh|bash"
          rg --ignore --hidden -l "^#!(.*/|.*env +)($SUPPORTED_SHELLS)" . \
              | xargs -r -t shfmt -d -i 4 -s -bn -ci -sr -kp

      - name: Run stylua
        if: always()
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: . -c

  linters:
    name: Shellcheck & Luacheck
    runs-on: ubuntu-latest
    needs: [formatters]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Run ShellCheck (no ZSH)
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: >-
            ./shell/.zshrc
            ./shell/.zshenv
            ./**/*.zsh
        env:
          # SC1091: Not following. -- is fixed locally but CI still fails
          SHELLCHECK_OPTS: -e SC1091
      - name: Run ShellCheck (only ZSH)
        if: always()
        uses: ludeeus/action-shellcheck@master
        env:
          # SC1091: Not following. -- is fixed locally but CI still fails
          # -s bash: force checks as bash because of zsh not supported
          SHELLCHECK_OPTS: -e SC1091 -s bash
