[tools]
bat = "0.26.1"
carapace-bin = "1.7.3"
delta = "0.19.2"
eza = "0.23.5"
ffmpeg = "9.0.1"
fzf = "0.74.3"
jq = "1.8.2"
neovim = "0.12.5"
opencode = "1.18.26"
ripgrep = "15.2.0"
starship = "1.26.0"
vivid = "0.10.1"

[tool_alias]
carapace-bin = "asdf:vic1707/asdf-carapace-bin"
vivid = "asdf:vic1707/asdf-any-cargo-quickinstall" # default one gets x86_64 on mac m

[settings]
idiomatic_version_file_enable_tools = []

## Not working on Mac Apple Silicon ##
# imagemagick = "7.1.2-13"
