[tools]
bat = "0.26.1"
bun = "latest"
carapace-bin = "1.7.1"
delta = "0.19.2"
eza = "0.23.4"
ffmpeg = "8.1.2"
fzf = "0.73.1"
jq = "1.8.2"
neovim = "0.12.3"
ripgrep = "15.1.0"
starship = "1.25.1"
vivid = "0.10.1"

[tool_alias]
carapace-bin = "asdf:vic1707/asdf-carapace-bin"
vivid = "asdf:vic1707/asdf-any-cargo-quickinstall" # default one gets x86_64 on mac m

[settings]
idiomatic_version_file_enable_tools = []

## Not working on Mac Apple Silicon ##
# imagemagick = "7.1.2-13"
